# Paso 1: Utilizar una imagen base con Node.js v18.16.0
FROM node:18.16.0

# Paso 2: Establecer el directorio de trabajo en el contenedor
WORKDIR /usr/src/app

# Paso 3: Copiar los archivos de dependencias del proyecto
COPY package*.json ./

# Paso 4: Instalar las dependencias
RUN npm install

# Paso 5: Copiar todos los archivos del proyecto al contenedor
COPY . .

# Paso 6: Compilar la aplicación (si es necesario)
RUN npm run build

# Paso 7: Exponer el puerto en el que se ejecutará la aplicación
EXPOSE 3000

# Paso 8: Definir el comando para ejecutar la aplicación
CMD ["npm", "run", "start:prod"]
