export enum Event {
    MARKETER_WELCOME = 'MARKETER_WELCOME',
    MARKETER_REQUEST_RUC_DNI = 'MARKETER_REQUEST_RUC_DNI',
    MARKETER_REQUEST_BUSINESS_NAME = 'MARKETER_REQUEST_BUSINESS_NAME',
    MARKETER_REQUEST_BUSINESS_LOCATION = 'MARKETER_REQUEST_BUSINESS_LOCATION',
    MARKETER_REQUEST_QR_CODE = 'MARKETER_REQUEST_QR_CODE',
    MARKETER_SUCCESS_CONFIRM = 'MARKETER_SUCCESS_CONFIRM',
}