export enum PAYMENTSTATUS {
  PENDING = 1,
  ACCEPTED = 2,
  REJECTED = 3,
}
export const STEPS = {
  INIT: '0',
  SEND_GREETINGS: '1',
  PUT_DNI: '2',
  INSERT_DATE: '3',
  SELECT_PROVIDER: '4',
  SELECT_PAYMENT: '5',
  SUBMIT_VOUCHER: '6',
  SEND_CONFIRMATION: '7',
  INFO_FOR_NEW_PROVIDER: '8',
};
