export const STEPS = {
  CHAT_GTP: '-1',
  INIT: '0',
  SELECT_SPECIALTY: '1',
  INSERT_DATE: '2',
  SELECT_DOCTOR: '3',
  SELECT_PAYMENT: '4',
  SUBMIT_VOUCHER: '5',
  SEND_CONFIRMATION: '6',
};

export enum PAYMENTSTATUS {
  PENDING = "1",
  ACCEPTED = "2",
  REJECTED = "3"
}
