export enum PAYMENTSTATUS {
  PENDING = 1,
  ACCEPTED = 2,
  REJECTED = 3,
}
export const STEPS = {
  INIT: '0',
  PUT_DNI: '1',
  INSERT_DATE: '2',
  SELECT_PROVIDER: '3',
  SELECT_PAYMENT: '4',
  SUBMIT_VOUCHER: '5',
  SEND_CONFIRMATION: '6',
};
